# GoReleaser configuration for Drop CLI
project_name: drop

builds:
  - id: drop-client
    binary: drop
    main: ./cmd/client
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: drop-client
    builds:
      - drop-client
    name_template: "drop_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: marianozunino
    name: drop
  draft: false
  prerelease: auto
  mode: replace
  name_template: 'Release {{ .Tag }}'
  header: |
    ## 🚀 Drop CLI {{ .Tag }}
    
    Download the appropriate binary for your platform:
    
    ### Linux
    - **AMD64**: [drop_linux_amd64.tar.gz](https://github.com/marianozunino/drop/releases/download/{{ .Tag }}/drop_linux_amd64.tar.gz)
    - **ARM64**: [drop_linux_arm64.tar.gz](https://github.com/marianozunino/drop/releases/download/{{ .Tag }}/drop_linux_arm64.tar.gz)
    
    ### macOS
    - **AMD64**: [drop_darwin_amd64.tar.gz](https://github.com/marianozunino/drop/releases/download/{{ .Tag }}/drop_darwin_amd64.tar.gz)
    - **ARM64**: [drop_darwin_arm64.tar.gz](https://github.com/marianozunino/drop/releases/download/{{ .Tag }}/drop_darwin_arm64.tar.gz)
    
    ### Windows
    - **AMD64**: [drop_windows_amd64.zip](https://github.com/marianozunino/drop/releases/download/{{ .Tag }}/drop_windows_amd64.zip)
    - **ARM64**: [drop_windows_arm64.zip](https://github.com/marianozunino/drop/releases/download/{{ .Tag }}/drop_windows_arm64.zip)
    
    ### Quick Install
    ```bash
    # Linux/macOS
    curl -L https://github.com/marianozunino/drop/releases/latest/download/drop_linux_amd64.tar.gz | tar -xz
    sudo mv drop /usr/local/bin/
    
    # Or using the install script
    curl -fsSL https://raw.githubusercontent.com/marianozunino/drop/main/scripts/install.sh | sh
    ```

  footer: |
    ## Installation
    
    ### Using the install script (recommended)
    ```bash
    curl -fsSL https://raw.githubusercontent.com/marianozunino/drop/main/scripts/install.sh | sh
    ```
    
    ### Manual installation
    1. Download the appropriate binary for your platform from the assets above
    2. Extract the archive
    3. Move the `drop` binary to a directory in your PATH (e.g., `/usr/local/bin/`)
    4. Make it executable: `chmod +x drop`
    
    ### Verify installation
    ```bash
    drop --version
    drop --help
    ```

# Docker builds are handled separately by GitHub Actions
# This keeps CLI releases focused on binaries only
