// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminSettingsPanel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-show=\"showSettings\" class=\"settings-panel\"><h3>Admin Settings</h3><div class=\"settings-content\"><div class=\"setting-item\"><label><input type=\"checkbox\" x-model=\"settings.noConfirmDelete\" @change=\"saveSettings()\"> Skip delete confirmation dialogs</label></div><div class=\"setting-item\"><label><input type=\"checkbox\" x-model=\"settings.autoRefresh\" @change=\"saveSettings()\"> Auto-refresh dashboard every 30 seconds</label></div><div class=\"setting-item\"><label><input type=\"checkbox\" x-model=\"settings.compactView\" @change=\"saveSettings()\"> Compact table view</label></div><div class=\"setting-item\"><label><input type=\"checkbox\" x-model=\"settings.showFileSize\" @change=\"saveSettings()\"> Show file sizes in table</label></div><div class=\"setting-item\"><label><input type=\"checkbox\" x-model=\"settings.showUploadDate\" @change=\"saveSettings()\"> Show upload dates in table</label></div></div><div class=\"settings-actions\"><button @click=\"resetSettings()\">Reset to Defaults</button> <button @click=\"showSettings = false\">Close</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
